'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class AccountingPeriods
        Inherits XPObject
        Dim fArPeriodName As String
        Public Property ArPeriodName() As String
            Get
                Return fArPeriodName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArPeriodName", fArPeriodName, value)
            End Set
        End Property
        Dim fEnPeriodName As String
        Public Property EnPeriodName() As String
            Get
                Return fEnPeriodName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EnPeriodName", fEnPeriodName, value)
            End Set
        End Property
        Dim fFromDate As DateTime
        Public Property FromDate() As DateTime
            Get
                Return fFromDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FromDate", fFromDate, value)
            End Set
        End Property
        Dim fToDate As DateTime
        Public Property ToDate() As DateTime
            Get
                Return fToDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("ToDate", fToDate, value)
            End Set
        End Property
        Dim fNotes As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
    End Class

End Namespace
