'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class BankGroups
        Inherits XPObject
        Dim fArGroupName As String
        Public Property ArGroupName() As String
            Get
                Return fArGroupName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArGroupName", fArGroupName, value)
            End Set
        End Property
        Dim fEnGroupName As String
        Public Property EnGroupName() As String
            Get
                Return fEnGroupName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EnGroupName", fEnGroupName, value)
            End Set
        End Property
        Dim fParentGroup As BankGroups
        Public Property ParentGroup() As BankGroups
            Get
                Return fParentGroup
            End Get
            Set(ByVal value As BankGroups)
                SetPropertyValue(Of BankGroups)("ParentGroup", fParentGroup, value)
            End Set
        End Property
        Dim fNotes As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
    End Class

End Namespace
