'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class Banks
        Inherits XPObject
        Dim fArBankName As String
        Public Property ArBankName() As String
            Get
                Return fArBankName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArBankName", fArBankName, value)
            End Set
        End Property
        Dim fEnBankName As String
        Public Property EnBankName() As String
            Get
                Return fEnBankName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EnBankName", fEnBankName, value)
            End Set
        End Property
        Dim fAccountNo As String
        Public Property AccountNo() As String
            Get
                Return fAccountNo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AccountNo", fAccountNo, value)
            End Set
        End Property
        Dim fIBAN As String
        Public Property IBAN() As String
            Get
                Return fIBAN
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("IBAN", fIBAN, value)
            End Set
        End Property
        Dim fAddress As String
        Public Property Address() As String
            Get
                Return fAddress
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Address", fAddress, value)
            End Set
        End Property
        Dim fBankGroup As BankGroups
        Public Property BankGroup() As BankGroups
            Get
                Return fBankGroup
            End Get
            Set(ByVal value As BankGroups)
                SetPropertyValue(Of BankGroups)("BankGroup", fBankGroup, value)
            End Set
        End Property
        Dim fCurrency As Currencies
        Public Property Currency() As Currencies
            Get
                Return fCurrency
            End Get
            Set(ByVal value As Currencies)
                SetPropertyValue(Of Currencies)("Currency", fCurrency, value)
            End Set
        End Property
        Dim fGlAccount As ChartOfAccount
        Public Property GlAccount() As ChartOfAccount
            Get
                Return fGlAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("GlAccount", fGlAccount, value)
            End Set
        End Property
        Dim fIsAutoGenerateAccount As Boolean
        Public Property IsAutoGenerateAccount() As Boolean
            Get
                Return fIsAutoGenerateAccount
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsAutoGenerateAccount", fIsAutoGenerateAccount, value)
            End Set
        End Property
        Dim fLimit As Decimal
        Public Property Limit() As Decimal
            Get
                Return fLimit
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Limit", fLimit, value)
            End Set
        End Property
        Dim fNotes As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
    End Class

End Namespace
