'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class Budgets
        Inherits XPObject
        Dim fArName As String
        Public Property ArName() As String
            Get
                Return fArName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArName", fArName, value)
            End Set
        End Property
        Dim fEnName As String
        Public Property EnName() As String
            Get
                Return fEnName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EnName", fEnName, value)
            End Set
        End Property
        Dim fNotes As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
        <Association("BudgetItemsReferencesBudgets", GetType(BudgetItems)), Aggregated()> _
        Public ReadOnly Property BudgetItemsCollection() As XPCollection(Of BudgetItems)
            Get
                Return GetCollection(Of BudgetItems)("BudgetItemsCollection")
            End Get
        End Property
    End Class

End Namespace
