'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class BudgetItems
        Inherits XPObject
        Dim fBudget As Budgets
        <Association("BudgetItemsReferencesBudgets")> _
        Public Property Budget() As Budgets
            Get
                Return fBudget
            End Get
            Set(ByVal value As Budgets)
                SetPropertyValue(Of Budgets)("Budget", fBudget, value)
            End Set
        End Property
        Dim fDebit As Decimal
        Public Property Debit() As Decimal
            Get
                Return fDebit
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Debit", fDebit, value)
            End Set
        End Property
        Dim fCredit As Decimal
        Public Property Credit() As Decimal
            Get
                Return fCredit
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Credit", fCredit, value)
            End Set
        End Property
        Dim fGlAccount As ChartOfAccount
        Public Property GlAccount() As ChartOfAccount
            Get
                Return fGlAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("GlAccount", fGlAccount, value)
            End Set
        End Property
        Dim fCostCenter As CostCenters
        Public Property CostCenter() As CostCenters
            Get
                Return fCostCenter
            End Get
            Set(ByVal value As CostCenters)
                SetPropertyValue(Of CostCenters)("CostCenter", fCostCenter, value)
            End Set
        End Property
        Dim fCurrency As Currencies
        Public Property Currency() As Currencies
            Get
                Return fCurrency
            End Get
            Set(ByVal value As Currencies)
                SetPropertyValue(Of Currencies)("Currency", fCurrency, value)
            End Set
        End Property
        Dim fAccountingPeriod As AccountingPeriods
        Public Property AccountingPeriod() As AccountingPeriods
            Get
                Return fAccountingPeriod
            End Get
            Set(ByVal value As AccountingPeriods)
                SetPropertyValue(Of AccountingPeriods)("AccountingPeriod", fAccountingPeriod, value)
            End Set
        End Property
        Dim fNotes As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
    End Class

End Namespace
