'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class Configurations
        Inherits XPObject
        Dim fScope As String
        Public Property Scope() As String
            Get
                Return fScope
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Scope", fScope, value)
            End Set
        End Property
        Dim fConfiguration As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Configuration() As String
            Get
                Return fConfiguration
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Configuration", fConfiguration, value)
            End Set
        End Property
        Dim fIsAutoLoad As Boolean
        Public Property IsAutoLoad() As Boolean
            Get
                Return fIsAutoLoad
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsAutoLoad", fIsAutoLoad, value)
            End Set
        End Property
    End Class

End Namespace
