'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class ContactPayments
        Inherits XPObject
        Dim fContact_ As String
        Public Property Contact_() As String
            Get
                Return fContact_
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Contact_", fContact_, value)
            End Set
        End Property
        Dim fPaymentType As PaymentTypes
        Public Property PaymentType() As PaymentTypes
            Get
                Return fPaymentType
            End Get
            Set(ByVal value As PaymentTypes)
                SetPropertyValue(Of PaymentTypes)("PaymentType", fPaymentType, value)
            End Set
        End Property
    End Class

End Namespace
