'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class CostCenterAccounts
        Inherits XPObject
        Dim fCostCenter As CostCenters
        <Association("CostCenterAccountsReferencesCostCenters")> _
        Public Property CostCenter() As CostCenters
            Get
                Return fCostCenter
            End Get
            Set(ByVal value As CostCenters)
                SetPropertyValue(Of CostCenters)("CostCenter", fCostCenter, value)
            End Set
        End Property
        Dim fGlAccount As ChartOfAccount
        Public Property GlAccount() As ChartOfAccount
            Get
                Return fGlAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("GlAccount", fGlAccount, value)
            End Set
        End Property
        Dim fRate As Decimal
        Public Property Rate() As Decimal
            Get
                Return fRate
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Rate", fRate, value)
            End Set
        End Property
    End Class

End Namespace
