'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class CostCenters
        Inherits XPObject
        Dim fCode As String
        Public Property Code() As String
            Get
                Return fCode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Code", fCode, value)
            End Set
        End Property
        Dim fArCostCenterName As String
        Public Property ArCostCenterName() As String
            Get
                Return fArCostCenterName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArCostCenterName", fArCostCenterName, value)
            End Set
        End Property
        Dim fEnCostCenterName As String
        Public Property EnCostCenterName() As String
            Get
                Return fEnCostCenterName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EnCostCenterName", fEnCostCenterName, value)
            End Set
        End Property
        Dim fParentCostCenter As CostCenters
        Public Property ParentCostCenter() As CostCenters
            Get
                Return fParentCostCenter
            End Get
            Set(ByVal value As CostCenters)
                SetPropertyValue(Of CostCenters)("ParentCostCenter", fParentCostCenter, value)
            End Set
        End Property
        Dim fNotes As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
        <Association("CostCenterAccountsReferencesCostCenters", GetType(CostCenterAccounts)), Aggregated()> _
        Public ReadOnly Property CostCenterAccountsCollection() As XPCollection(Of CostCenterAccounts)
            Get
                Return GetCollection(Of CostCenterAccounts)("CostCenterAccountsCollection")
            End Get
        End Property
    End Class

End Namespace
