'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class CurrencyUnit
        Inherits XPObject
        Dim fCurrency As Currencies
        <Association("CurrencyUnitReferencesCurrencies")> _
        Public Property Currency() As Currencies
            Get
                Return fCurrency
            End Get
            Set(ByVal value As Currencies)
                SetPropertyValue(Of Currencies)("Currency", fCurrency, value)
            End Set
        End Property
        Dim fUnit As Integer
        Public Property Unit() As Integer
            Get
                Return fUnit
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Unit", fUnit, value)
            End Set
        End Property
    End Class

End Namespace
