'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class DocumentComments
        Inherits XPObject
        Dim fDocument As Documents
        Public Property Document() As Documents
            Get
                Return fDocument
            End Get
            Set(ByVal value As Documents)
                SetPropertyValue(Of Documents)("Document", fDocument, value)
            End Set
        End Property
        Dim fCommentBy As SystemUsers
        Public Property CommentBy() As SystemUsers
            Get
                Return fCommentBy
            End Get
            Set(ByVal value As SystemUsers)
                SetPropertyValue(Of SystemUsers)("CommentBy", fCommentBy, value)
            End Set
        End Property
        Dim fCommentDate As DateTime
        Public Property CommentDate() As DateTime
            Get
                Return fCommentDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CommentDate", fCommentDate, value)
            End Set
        End Property
        Dim fComment As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Comment() As String
            Get
                Return fComment
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Comment", fComment, value)
            End Set
        End Property
        Dim fIsEnable As Boolean
        Public Property IsEnable() As Boolean
            Get
                Return fIsEnable
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsEnable", fIsEnable, value)
            End Set
        End Property
    End Class

End Namespace
