'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class DocumentTypes
        Inherits XPObject
        Dim fArTypeName As String
        Public Property ArTypeName() As String
            Get
                Return fArTypeName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArTypeName", fArTypeName, value)
            End Set
        End Property
        Dim fEnTypeName As String
        Public Property EnTypeName() As String
            Get
                Return fEnTypeName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EnTypeName", fEnTypeName, value)
            End Set
        End Property
        Dim fCreditAccount As ChartOfAccount
        Public Property CreditAccount() As ChartOfAccount
            Get
                Return fCreditAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("CreditAccount", fCreditAccount, value)
            End Set
        End Property
        Dim fDebitAccount As ChartOfAccount
        Public Property DebitAccount() As ChartOfAccount
            Get
                Return fDebitAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("DebitAccount", fDebitAccount, value)
            End Set
        End Property
        Dim fCostAccount As ChartOfAccount
        Public Property CostAccount() As ChartOfAccount
            Get
                Return fCostAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("CostAccount", fCostAccount, value)
            End Set
        End Property
        Dim fInventoryAccount As ChartOfAccount
        Public Property InventoryAccount() As ChartOfAccount
            Get
                Return fInventoryAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("InventoryAccount", fInventoryAccount, value)
            End Set
        End Property
        Dim fDiscountAccount As ChartOfAccount
        Public Property DiscountAccount() As ChartOfAccount
            Get
                Return fDiscountAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("DiscountAccount", fDiscountAccount, value)
            End Set
        End Property
        Dim fExtraAccount As ChartOfAccount
        Public Property ExtraAccount() As ChartOfAccount
            Get
                Return fExtraAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("ExtraAccount", fExtraAccount, value)
            End Set
        End Property
        Dim fCommissionAccount As ChartOfAccount
        Public Property CommissionAccount() As ChartOfAccount
            Get
                Return fCommissionAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("CommissionAccount", fCommissionAccount, value)
            End Set
        End Property
        Dim fActionType As String
        Public Property ActionType() As String
            Get
                Return fActionType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ActionType", fActionType, value)
            End Set
        End Property
        Dim fIsStoreEffect As Boolean
        Public Property IsStoreEffect() As Boolean
            Get
                Return fIsStoreEffect
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsStoreEffect", fIsStoreEffect, value)
            End Set
        End Property
        Dim fAutoEffectStore As Boolean
        Public Property AutoEffectStore() As Boolean
            Get
                Return fAutoEffectStore
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("AutoEffectStore", fAutoEffectStore, value)
            End Set
        End Property
        Dim fIsGenerateVoucher As Boolean
        Public Property IsGenerateVoucher() As Boolean
            Get
                Return fIsGenerateVoucher
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsGenerateVoucher", fIsGenerateVoucher, value)
            End Set
        End Property
        Dim fAutoGenerateVoucher As Boolean
        Public Property AutoGenerateVoucher() As Boolean
            Get
                Return fAutoGenerateVoucher
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("AutoGenerateVoucher", fAutoGenerateVoucher, value)
            End Set
        End Property
        Dim fIsReturnedBill As Boolean
        Public Property IsReturnedBill() As Boolean
            Get
                Return fIsReturnedBill
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsReturnedBill", fIsReturnedBill, value)
            End Set
        End Property
        Dim fIsEffectLastSalePurchasePrice As Boolean
        Public Property IsEffectLastSalePurchasePrice() As Boolean
            Get
                Return fIsEffectLastSalePurchasePrice
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsEffectLastSalePurchasePrice", fIsEffectLastSalePurchasePrice, value)
            End Set
        End Property
        Dim fIsEffectAveragePrice As Boolean
        Public Property IsEffectAveragePrice() As Boolean
            Get
                Return fIsEffectAveragePrice
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsEffectAveragePrice", fIsEffectAveragePrice, value)
            End Set
        End Property
        Dim fIsUseClassStore As Boolean
        Public Property IsUseClassStore() As Boolean
            Get
                Return fIsUseClassStore
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsUseClassStore", fIsUseClassStore, value)
            End Set
        End Property
    End Class

End Namespace
