'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class DocumentApprovals
        Inherits XPObject
        Dim fDocument As Documents
        Public Property Document() As Documents
            Get
                Return fDocument
            End Get
            Set(ByVal value As Documents)
                SetPropertyValue(Of Documents)("Document", fDocument, value)
            End Set
        End Property
        Dim fDocumentProcess As DocumentProcesses
        Public Property DocumentProcess() As DocumentProcesses
            Get
                Return fDocumentProcess
            End Get
            Set(ByVal value As DocumentProcesses)
                SetPropertyValue(Of DocumentProcesses)("DocumentProcess", fDocumentProcess, value)
            End Set
        End Property
        Dim fIsApproved As Boolean
        Public Property IsApproved() As Boolean
            Get
                Return fIsApproved
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsApproved", fIsApproved, value)
            End Set
        End Property
        Dim fApprovedBy As SystemUsers
        Public Property ApprovedBy() As SystemUsers
            Get
                Return fApprovedBy
            End Get
            Set(ByVal value As SystemUsers)
                SetPropertyValue(Of SystemUsers)("ApprovedBy", fApprovedBy, value)
            End Set
        End Property
        Dim fApprovedOn As DateTime
        Public Property ApprovedOn() As DateTime
            Get
                Return fApprovedOn
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("ApprovedOn", fApprovedOn, value)
            End Set
        End Property
        Dim fNotes As String
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
    End Class

End Namespace
