'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class DocumentProcesses
        Inherits XPObject
        Dim fDocumentType As DocumentTypes
        Public Property DocumentType() As DocumentTypes
            Get
                Return fDocumentType
            End Get
            Set(ByVal value As DocumentTypes)
                SetPropertyValue(Of DocumentTypes)("DocumentType", fDocumentType, value)
            End Set
        End Property
        Dim fBusinessProccess As DocumentProcesses
        Public Property BusinessProccess() As DocumentProcesses
            Get
                Return fBusinessProccess
            End Get
            Set(ByVal value As DocumentProcesses)
                SetPropertyValue(Of DocumentProcesses)("BusinessProccess", fBusinessProccess, value)
            End Set
        End Property
        Dim fRequireRole As Roles
        Public Property RequireRole() As Roles
            Get
                Return fRequireRole
            End Get
            Set(ByVal value As Roles)
                SetPropertyValue(Of Roles)("RequireRole", fRequireRole, value)
            End Set
        End Property
    End Class

End Namespace
