'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class Documents
        Inherits XPObject
        Dim fDocumentType As DocumentTypes
        Public Property DocumentType() As DocumentTypes
            Get
                Return fDocumentType
            End Get
            Set(ByVal value As DocumentTypes)
                SetPropertyValue(Of DocumentTypes)("DocumentType", fDocumentType, value)
            End Set
        End Property
        Dim fCreatedBy As SystemUsers
        Public Property CreatedBy() As SystemUsers
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As SystemUsers)
                SetPropertyValue(Of SystemUsers)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedOn As DateTime
        Public Property CreatedOn() As DateTime
            Get
                Return fCreatedOn
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedOn", fCreatedOn, value)
            End Set
        End Property
        Dim fUpdatedBy As SystemUsers
        Public Property UpdatedBy() As SystemUsers
            Get
                Return fUpdatedBy
            End Get
            Set(ByVal value As SystemUsers)
                SetPropertyValue(Of SystemUsers)("UpdatedBy", fUpdatedBy, value)
            End Set
        End Property
        Dim fUpdatedOn As DateTime
        Public Property UpdatedOn() As DateTime
            Get
                Return fUpdatedOn
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("UpdatedOn", fUpdatedOn, value)
            End Set
        End Property
        Dim fCurrency As Currencies
        Public Property Currency() As Currencies
            Get
                Return fCurrency
            End Get
            Set(ByVal value As Currencies)
                SetPropertyValue(Of Currencies)("Currency", fCurrency, value)
            End Set
        End Property
        Dim fCurrencyRate As Decimal
        Public Property CurrencyRate() As Decimal
            Get
                Return fCurrencyRate
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("CurrencyRate", fCurrencyRate, value)
            End Set
        End Property
        Dim fHijryDate As String
        Public Property HijryDate() As String
            Get
                Return fHijryDate
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("HijryDate", fHijryDate, value)
            End Set
        End Property
        Dim fEditable As Boolean
        Public Property Editable() As Boolean
            Get
                Return fEditable
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("Editable", fEditable, value)
            End Set
        End Property
        Dim fRefranceNumber As String
        Public Property RefranceNumber() As String
            Get
                Return fRefranceNumber
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RefranceNumber", fRefranceNumber, value)
            End Set
        End Property
        Dim fNotes As String
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
    End Class

End Namespace
