'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class DocumentEvents
        Inherits XPObject
        Dim fDocument As Documents
        Public Property Document() As Documents
            Get
                Return fDocument
            End Get
            Set(ByVal value As Documents)
                SetPropertyValue(Of Documents)("Document", fDocument, value)
            End Set
        End Property
        Dim fEventType_ As String
        Public Property EventType_() As String
            Get
                Return fEventType_
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EventType_", fEventType_, value)
            End Set
        End Property
        Dim fDays As DateTime
        Public Property Days() As DateTime
            Get
                Return fDays
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("Days", fDays, value)
            End Set
        End Property
        Dim fIsDisplayInNotifications As Boolean
        Public Property IsDisplayInNotifications() As Boolean
            Get
                Return fIsDisplayInNotifications
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsDisplayInNotifications", fIsDisplayInNotifications, value)
            End Set
        End Property
        Dim fIsBefore As Boolean
        Public Property IsBefore() As Boolean
            Get
                Return fIsBefore
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsBefore", fIsBefore, value)
            End Set
        End Property
        Dim fIsAfter As Boolean
        Public Property IsAfter() As Boolean
            Get
                Return fIsAfter
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsAfter", fIsAfter, value)
            End Set
        End Property
        Dim fEventDate As DateTime
        Public Property EventDate() As DateTime
            Get
                Return fEventDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("EventDate", fEventDate, value)
            End Set
        End Property
        Dim fCompletedOn As DateTime
        Public Property CompletedOn() As DateTime
            Get
                Return fCompletedOn
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CompletedOn", fCompletedOn, value)
            End Set
        End Property
    End Class

End Namespace
