'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class DocumentAttachments
        Inherits XPObject
        Dim fDocument As Documents
        Public Property Document() As Documents
            Get
                Return fDocument
            End Get
            Set(ByVal value As Documents)
                SetPropertyValue(Of Documents)("Document", fDocument, value)
            End Set
        End Property
        Dim fAttachmentDate As DateTime
        Public Property AttachmentDate() As DateTime
            Get
                Return fAttachmentDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("AttachmentDate", fAttachmentDate, value)
            End Set
        End Property
        Dim fAttachedBy As SystemUsers
        Public Property AttachedBy() As SystemUsers
            Get
                Return fAttachedBy
            End Get
            Set(ByVal value As SystemUsers)
                SetPropertyValue(Of SystemUsers)("AttachedBy", fAttachedBy, value)
            End Set
        End Property
        Dim fHijryDate As String
        Public Property HijryDate() As String
            Get
                Return fHijryDate
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("HijryDate", fHijryDate, value)
            End Set
        End Property
        Dim fAttachmentFile As String
        Public Property AttachmentFile() As String
            Get
                Return fAttachmentFile
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AttachmentFile", fAttachmentFile, value)
            End Set
        End Property
        Dim fNotes As String
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
    End Class

End Namespace
