'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class GridLayouts
        Inherits XPObject
        Dim fFormName As String
        Public Property FormName() As String
            Get
                Return fFormName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("FormName", fFormName, value)
            End Set
        End Property
        Dim fGridName As String
        Public Property GridName() As String
            Get
                Return fGridName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("GridName", fGridName, value)
            End Set
        End Property
        Dim fLanguage As String
        Public Property Language() As String
            Get
                Return fLanguage
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Language", fLanguage, value)
            End Set
        End Property
        Dim fLayoutData As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property LayoutData() As String
            Get
                Return fLayoutData
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("LayoutData", fLayoutData, value)
            End Set
        End Property
    End Class

End Namespace
