'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class Installment
        Inherits XPObject
        Dim fGlAccount As ChartOfAccount
        Public Property GlAccount() As ChartOfAccount
            Get
                Return fGlAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("GlAccount", fGlAccount, value)
            End Set
        End Property
        Dim fCurrency As Currencies
        Public Property Currency() As Currencies
            Get
                Return fCurrency
            End Get
            Set(ByVal value As Currencies)
                SetPropertyValue(Of Currencies)("Currency", fCurrency, value)
            End Set
        End Property
        Dim fInstallmentType As String
        Public Property InstallmentType() As String
            Get
                Return fInstallmentType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("InstallmentType", fInstallmentType, value)
            End Set
        End Property
        Dim fTotalAmount As Decimal
        Public Property TotalAmount() As Decimal
            Get
                Return fTotalAmount
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotalAmount", fTotalAmount, value)
            End Set
        End Property
        Dim fPaymentCount As Integer
        Public Property PaymentCount() As Integer
            Get
                Return fPaymentCount
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("PaymentCount", fPaymentCount, value)
            End Set
        End Property
        Dim fTimeFrameByDays As Integer
        Public Property TimeFrameByDays() As Integer
            Get
                Return fTimeFrameByDays
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("TimeFrameByDays", fTimeFrameByDays, value)
            End Set
        End Property
        Dim fFirstPaymentDate As DateTime
        Public Property FirstPaymentDate() As DateTime
            Get
                Return fFirstPaymentDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FirstPaymentDate", fFirstPaymentDate, value)
            End Set
        End Property
        Dim fNotes As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
    End Class

End Namespace
