'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class Items
        Inherits XPObject
        Dim fCode As String
        Public Property Code() As String
            Get
                Return fCode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Code", fCode, value)
            End Set
        End Property
        Dim fBarcode As String
        Public Property Barcode() As String
            Get
                Return fBarcode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Barcode", fBarcode, value)
            End Set
        End Property
        Dim fArItemName As String
        Public Property ArItemName() As String
            Get
                Return fArItemName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArItemName", fArItemName, value)
            End Set
        End Property
        Dim fEnItemName As String
        Public Property EnItemName() As String
            Get
                Return fEnItemName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EnItemName", fEnItemName, value)
            End Set
        End Property
        Dim fCompany As String
        Public Property Company() As String
            Get
                Return fCompany
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Company", fCompany, value)
            End Set
        End Property
        Dim fDescriptions As String
        Public Property Descriptions() As String
            Get
                Return fDescriptions
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Descriptions", fDescriptions, value)
            End Set
        End Property
        Dim fIsStockControl As Boolean
        Public Property IsStockControl() As Boolean
            Get
                Return fIsStockControl
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsStockControl", fIsStockControl, value)
            End Set
        End Property
        Dim fIsBatchNumber As Boolean
        Public Property IsBatchNumber() As Boolean
            Get
                Return fIsBatchNumber
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsBatchNumber", fIsBatchNumber, value)
            End Set
        End Property
        Dim fIsSerialNumber As Boolean
        Public Property IsSerialNumber() As Boolean
            Get
                Return fIsSerialNumber
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsSerialNumber", fIsSerialNumber, value)
            End Set
        End Property
        Dim fIsBonuesPoints As Boolean
        Public Property IsBonuesPoints() As Boolean
            Get
                Return fIsBonuesPoints
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsBonuesPoints", fIsBonuesPoints, value)
            End Set
        End Property
        Dim fIsDiscounted As Boolean
        Public Property IsDiscounted() As Boolean
            Get
                Return fIsDiscounted
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsDiscounted", fIsDiscounted, value)
            End Set
        End Property
        Dim fItemImage As System.Drawing.Image
        <Size(SizeAttribute.Unlimited)> _
        <ValueConverter(GetType(DevExpress.Xpo.Metadata.ImageValueConverter))> _
        Public Property ItemImage() As System.Drawing.Image
            Get
                Return fItemImage
            End Get
            Set(ByVal value As System.Drawing.Image)
                SetPropertyValue(Of System.Drawing.Image)("ItemImage", fItemImage, value)
            End Set
        End Property
        Dim fCostingMethod As String
        Public Property CostingMethod() As String
            Get
                Return fCostingMethod
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CostingMethod", fCostingMethod, value)
            End Set
        End Property
        Dim fBaseUOM As ItemUOM
        Public Property BaseUOM() As ItemUOM
            Get
                Return fBaseUOM
            End Get
            Set(ByVal value As ItemUOM)
                SetPropertyValue(Of ItemUOM)("BaseUOM", fBaseUOM, value)
            End Set
        End Property
        Dim fSaleUOM As ItemUOM
        Public Property SaleUOM() As ItemUOM
            Get
                Return fSaleUOM
            End Get
            Set(ByVal value As ItemUOM)
                SetPropertyValue(Of ItemUOM)("SaleUOM", fSaleUOM, value)
            End Set
        End Property
        Dim fPurchaseUOM As ItemUOM
        Public Property PurchaseUOM() As ItemUOM
            Get
                Return fPurchaseUOM
            End Get
            Set(ByVal value As ItemUOM)
                SetPropertyValue(Of ItemUOM)("PurchaseUOM", fPurchaseUOM, value)
            End Set
        End Property
        <Association("ItemUOMReferencesItems", GetType(ItemUOM)), Aggregated()> _
        Public ReadOnly Property ItemUOMs() As XPCollection(Of ItemUOM)
            Get
                Return GetCollection(Of ItemUOM)("ItemUOMs")
            End Get
        End Property
    End Class

End Namespace
