'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class PaymentStatus
        Inherits XPObject
        Dim fStatusName As String
        Public Property StatusName() As String
            Get
                Return fStatusName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("StatusName", fStatusName, value)
            End Set
        End Property
        Dim fMarkAsPaid As Boolean
        Public Property MarkAsPaid() As Boolean
            Get
                Return fMarkAsPaid
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("MarkAsPaid", fMarkAsPaid, value)
            End Set
        End Property
        Dim fMarkAsRefund As Boolean
        Public Property MarkAsRefund() As Boolean
            Get
                Return fMarkAsRefund
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("MarkAsRefund", fMarkAsRefund, value)
            End Set
        End Property
        Dim fNotes As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
    End Class

End Namespace
