'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class PaymentTypes
        Inherits XPObject
        Dim fArPaymentName As String
        Public Property ArPaymentName() As String
            Get
                Return fArPaymentName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArPaymentName", fArPaymentName, value)
            End Set
        End Property
        Dim fEnPaymentName As String
        Public Property EnPaymentName() As String
            Get
                Return fEnPaymentName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EnPaymentName", fEnPaymentName, value)
            End Set
        End Property
        Dim fCashAccount As ChartOfAccount
        Public Property CashAccount() As ChartOfAccount
            Get
                Return fCashAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("CashAccount", fCashAccount, value)
            End Set
        End Property
        Dim fBaseAccount As ChartOfAccount
        Public Property BaseAccount() As ChartOfAccount
            Get
                Return fBaseAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("BaseAccount", fBaseAccount, value)
            End Set
        End Property
        Dim fPOS As PointOfSales
        Public Property POS() As PointOfSales
            Get
                Return fPOS
            End Get
            Set(ByVal value As PointOfSales)
                SetPropertyValue(Of PointOfSales)("POS", fPOS, value)
            End Set
        End Property
        Dim fIsIncome As Boolean
        Public Property IsIncome() As Boolean
            Get
                Return fIsIncome
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsIncome", fIsIncome, value)
            End Set
        End Property
        Dim fIsExpense As Boolean
        Public Property IsExpense() As Boolean
            Get
                Return fIsExpense
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsExpense", fIsExpense, value)
            End Set
        End Property
        Dim fIsShowClients As Boolean
        Public Property IsShowClients() As Boolean
            Get
                Return fIsShowClients
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsShowClients", fIsShowClients, value)
            End Set
        End Property
    End Class

End Namespace
