'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class Payments
        Inherits XPObject
        Dim fCreatedBy As SystemUsers
        Public Property CreatedBy() As SystemUsers
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As SystemUsers)
                SetPropertyValue(Of SystemUsers)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCreatedOn As DateTime
        Public Property CreatedOn() As DateTime
            Get
                Return fCreatedOn
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedOn", fCreatedOn, value)
            End Set
        End Property
        Dim fUpdatedBy As SystemUsers
        Public Property UpdatedBy() As SystemUsers
            Get
                Return fUpdatedBy
            End Get
            Set(ByVal value As SystemUsers)
                SetPropertyValue(Of SystemUsers)("UpdatedBy", fUpdatedBy, value)
            End Set
        End Property
        Dim fUpdatedOn As DateTime
        Public Property UpdatedOn() As DateTime
            Get
                Return fUpdatedOn
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("UpdatedOn", fUpdatedOn, value)
            End Set
        End Property
        Dim fHijryDate As String
        Public Property HijryDate() As String
            Get
                Return fHijryDate
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("HijryDate", fHijryDate, value)
            End Set
        End Property
        Dim fCode As String
        Public Property Code() As String
            Get
                Return fCode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Code", fCode, value)
            End Set
        End Property
        Dim fReferance As String
        Public Property Referance() As String
            Get
                Return fReferance
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Referance", fReferance, value)
            End Set
        End Property
        Dim fDocument As Documents
        Public Property Document() As Documents
            Get
                Return fDocument
            End Get
            Set(ByVal value As Documents)
                SetPropertyValue(Of Documents)("Document", fDocument, value)
            End Set
        End Property
        Dim fDescription As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        Dim fAmount As Decimal
        Public Property Amount() As Decimal
            Get
                Return fAmount
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Amount", fAmount, value)
            End Set
        End Property
        Dim fContactPayment As ContactPayments
        Public Property ContactPayment() As ContactPayments
            Get
                Return fContactPayment
            End Get
            Set(ByVal value As ContactPayments)
                SetPropertyValue(Of ContactPayments)("ContactPayment", fContactPayment, value)
            End Set
        End Property
        Dim fPaymentStatus As PaymentStatus
        Public Property PaymentStatus() As PaymentStatus
            Get
                Return fPaymentStatus
            End Get
            Set(ByVal value As PaymentStatus)
                SetPropertyValue(Of PaymentStatus)("PaymentStatus", fPaymentStatus, value)
            End Set
        End Property
        Dim fNotes As String
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
    End Class

End Namespace
