'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class Permissions
        Inherits XPObject
        Dim fCode As String
        Public Property Code() As String
            Get
                Return fCode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Code", fCode, value)
            End Set
        End Property
        Dim fDescription As String
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        <Association("TaskPermissionsReferencesPermissions", GetType(TaskPermissions)), Aggregated()> _
        Public ReadOnly Property PermissionsTaskCollection() As XPCollection(Of TaskPermissions)
            Get
                Return GetCollection(Of TaskPermissions)("PermissionsTaskCollection")
            End Get
        End Property
    End Class

End Namespace
