'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class Plugins
        Inherits XPObject
        Dim fGUID As Guid
        Public Property GUID() As Guid
            Get
                Return fGUID
            End Get
            Set(ByVal value As Guid)
                SetPropertyValue(Of Guid)("GUID", fGUID, value)
            End Set
        End Property
        Dim fPluginName As String
        Public Property PluginName() As String
            Get
                Return fPluginName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PluginName", fPluginName, value)
            End Set
        End Property
        Dim fDescription As String
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        Dim fLogo() As Byte
        Public Property Logo() As Byte()
            Get
                Return fLogo
            End Get
            Set(ByVal value As Byte())
                SetPropertyValue(Of Byte())("Logo", fLogo, value)
            End Set
        End Property
        Dim fIsEnabled As Boolean
        Public Property IsEnabled() As Boolean
            Get
                Return fIsEnabled
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsEnabled", fIsEnabled, value)
            End Set
        End Property
        <Association("TasksReferencesPlugins", GetType(Tasks)), Aggregated()> _
        Public ReadOnly Property TasksCollection() As XPCollection(Of Tasks)
            Get
                Return GetCollection(Of Tasks)("TasksCollection")
            End Get
        End Property
    End Class

End Namespace
