'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class SystemUsers
        Inherits XPObject
        Dim fFullName As String
        Public Property FullName() As String
            Get
                Return fFullName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("FullName", fFullName, value)
            End Set
        End Property
        Dim fDescriptions As String
        Public Property Descriptions() As String
            Get
                Return fDescriptions
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Descriptions", fDescriptions, value)
            End Set
        End Property
        Dim fUsername As String
        Public Property Username() As String
            Get
                Return fUsername
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Username", fUsername, value)
            End Set
        End Property
        Dim fPassword As String
        Public Property Password() As String
            Get
                Return fPassword
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Password", fPassword, value)
            End Set
        End Property
        Dim fIsAdmin As Boolean
        Public Property IsAdmin() As Boolean
            Get
                Return fIsAdmin
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsAdmin", fIsAdmin, value)
            End Set
        End Property
        Dim fIsActive As Boolean
        Public Property IsActive() As Boolean
            Get
                Return fIsActive
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsActive", fIsActive, value)
            End Set
        End Property
        Dim fIsOnline As Boolean
        Public Property IsOnline() As Boolean
            Get
                Return fIsOnline
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsOnline", fIsOnline, value)
            End Set
        End Property
        Dim fChangePasswordAfterLogon As Boolean
        Public Property ChangePasswordAfterLogon() As Boolean
            Get
                Return fChangePasswordAfterLogon
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("ChangePasswordAfterLogon", fChangePasswordAfterLogon, value)
            End Set
        End Property
        Dim fPhoto() As Byte
        Public Property Photo() As Byte()
            Get
                Return fPhoto
            End Get
            Set(ByVal value As Byte())
                SetPropertyValue(Of Byte())("Photo", fPhoto, value)
            End Set
        End Property
        Dim fNotes As String
        <Size(SizeAttribute.Unlimited)> _
        Public Property Notes() As String
            Get
                Return fNotes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Notes", fNotes, value)
            End Set
        End Property
        <Association("SessionsReferencesSystemUsers", GetType(Sessions)), Aggregated()> _
        Public ReadOnly Property SessionsCollection() As XPCollection(Of Sessions)
            Get
                Return GetCollection(Of Sessions)("SessionsCollection")
            End Get
        End Property
        <Association("UserRolesReferencesSystemUsers", GetType(UserRoles)), Aggregated()> _
        Public ReadOnly Property UserRolesCollection() As XPCollection(Of UserRoles)
            Get
                Return GetCollection(Of UserRoles)("UserRolesCollection")
            End Get
        End Property
    End Class

End Namespace
