'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class Tasks
        Inherits XPObject
        Dim fPlugin As Plugins
        <Association("TasksReferencesPlugins")> _
        Public Property Plugin() As Plugins
            Get
                Return fPlugin
            End Get
            Set(ByVal value As Plugins)
                SetPropertyValue(Of Plugins)("Plugin", fPlugin, value)
            End Set
        End Property
        Dim fScope As String
        Public Property Scope() As String
            Get
                Return fScope
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Scope", fScope, value)
            End Set
        End Property
        Dim fTarget As String
        Public Property Target() As String
            Get
                Return fTarget
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Target", fTarget, value)
            End Set
        End Property
        Dim fCode As String
        Public Property Code() As String
            Get
                Return fCode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Code", fCode, value)
            End Set
        End Property
        Dim fTaskName As String
        Public Property TaskName() As String
            Get
                Return fTaskName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("TaskName", fTaskName, value)
            End Set
        End Property
        <Association("TaskPermissionsReferencesTasks", GetType(TaskPermissions)), Aggregated()> _
        Public ReadOnly Property TaskPermissionsCollection() As XPCollection(Of TaskPermissions)
            Get
                Return GetCollection(Of TaskPermissions)("TaskPermissionsCollection")
            End Get
        End Property
    End Class

End Namespace
