'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class TaskPermissions
        Inherits XPObject
        Dim fTask As Tasks
        <Association("TaskPermissionsReferencesTasks")> _
        Public Property Task() As Tasks
            Get
                Return fTask
            End Get
            Set(ByVal value As Tasks)
                SetPropertyValue(Of Tasks)("Task", fTask, value)
            End Set
        End Property
        Dim fPermission As Permissions
        <Association("TaskPermissionsReferencesPermissions")> _
        Public Property Permission() As Permissions
            Get
                Return fPermission
            End Get
            Set(ByVal value As Permissions)
                SetPropertyValue(Of Permissions)("Permission", fPermission, value)
            End Set
        End Property
        <Association("RoleTaskPermessionsReferencesTaskPermissions", GetType(RoleTaskPermessions)), Aggregated()> _
        Public ReadOnly Property TaskPermessionsRoleCollection() As XPCollection(Of RoleTaskPermessions)
            Get
                Return GetCollection(Of RoleTaskPermessions)("TaskPermessionsRoleCollection")
            End Get
        End Property
    End Class

End Namespace
