'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class UserRoles
        Inherits XPObject
        Dim fUser As SystemUsers
        <Association("UserRolesReferencesSystemUsers")> _
        Public Property User() As SystemUsers
            Get
                Return fUser
            End Get
            Set(ByVal value As SystemUsers)
                SetPropertyValue(Of SystemUsers)("User", fUser, value)
            End Set
        End Property
        Dim fRole As Roles
        <Association("UserRolesReferencesRoles")> _
        Public Property Role() As Roles
            Get
                Return fRole
            End Get
            Set(ByVal value As Roles)
                SetPropertyValue(Of Roles)("Role", fRole, value)
            End Set
        End Property
    End Class

End Namespace
