'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.BASE.ORM

    <DeferredDeletion(True)> _
    Partial Public Class VoucherTypes
        Inherits XPObject
        Dim fArTypeName As String
        Public Property ArTypeName() As String
            Get
                Return fArTypeName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArTypeName", fArTypeName, value)
            End Set
        End Property
        Dim fEnTypeName As String
        Public Property EnTypeName() As String
            Get
                Return fEnTypeName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EnTypeName", fEnTypeName, value)
            End Set
        End Property
        Dim fCurrency As Currencies
        Public Property Currency() As Currencies
            Get
                Return fCurrency
            End Get
            Set(ByVal value As Currencies)
                SetPropertyValue(Of Currencies)("Currency", fCurrency, value)
            End Set
        End Property
        Dim fBaseAccount As ChartOfAccount
        Public Property BaseAccount() As ChartOfAccount
            Get
                Return fBaseAccount
            End Get
            Set(ByVal value As ChartOfAccount)
                SetPropertyValue(Of ChartOfAccount)("BaseAccount", fBaseAccount, value)
            End Set
        End Property
        Dim fCostCenter As CostCenters
        Public Property CostCenter() As CostCenters
            Get
                Return fCostCenter
            End Get
            Set(ByVal value As CostCenters)
                SetPropertyValue(Of CostCenters)("CostCenter", fCostCenter, value)
            End Set
        End Property
        Dim fIsCostCenterAffectAllAccounts As Boolean
        Public Property IsCostCenterAffectAllAccounts() As Boolean
            Get
                Return fIsCostCenterAffectAllAccounts
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsCostCenterAffectAllAccounts", fIsCostCenterAffectAllAccounts, value)
            End Set
        End Property
        Dim fIsWorkAsGeneralVoucher As Boolean
        Public Property IsWorkAsGeneralVoucher() As Boolean
            Get
                Return fIsWorkAsGeneralVoucher
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsWorkAsGeneralVoucher", fIsWorkAsGeneralVoucher, value)
            End Set
        End Property
        Dim fIsActAsCashVoucher As Boolean
        Public Property IsActAsCashVoucher() As Boolean
            Get
                Return fIsActAsCashVoucher
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsActAsCashVoucher", fIsActAsCashVoucher, value)
            End Set
        End Property
        Dim fIsActAsBillPayment As Boolean
        Public Property IsActAsBillPayment() As Boolean
            Get
                Return fIsActAsBillPayment
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsActAsBillPayment", fIsActAsBillPayment, value)
            End Set
        End Property
        Dim fIsAutoPostVoucher As Boolean
        Public Property IsAutoPostVoucher() As Boolean
            Get
                Return fIsAutoPostVoucher
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsAutoPostVoucher", fIsAutoPostVoucher, value)
            End Set
        End Property
        Dim fIsSelectClientAutomatically As Boolean
        Public Property IsSelectClientAutomatically() As Boolean
            Get
                Return fIsSelectClientAutomatically
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("IsSelectClientAutomatically", fIsSelectClientAutomatically, value)
            End Set
        End Property
        Dim fSerieStart As Integer
        Public Property SerieStart() As Integer
            Get
                Return fSerieStart
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("SerieStart", fSerieStart, value)
            End Set
        End Property
        Dim fNumOfPrintedCopies As Integer
        Public Property NumOfPrintedCopies() As Integer
            Get
                Return fNumOfPrintedCopies
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("NumOfPrintedCopies", fNumOfPrintedCopies, value)
            End Set
        End Property
    End Class

End Namespace
