'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class Accounts
        Inherits XPObject
        Dim fAccountName As String
        Public Property AccountName() As String
            Get
                Return fAccountName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AccountName", fAccountName, value)
            End Set
        End Property
        Dim fFirstName As String
        Public Property FirstName() As String
            Get
                Return fFirstName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("FirstName", fFirstName, value)
            End Set
        End Property
        Dim fLastName As String
        Public Property LastName() As String
            Get
                Return fLastName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("LastName", fLastName, value)
            End Set
        End Property
        Dim fAddress As String
        Public Property Address() As String
            Get
                Return fAddress
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Address", fAddress, value)
            End Set
        End Property
        Dim fCity As String
        Public Property City() As String
            Get
                Return fCity
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("City", fCity, value)
            End Set
        End Property
        Dim fState As String
        Public Property State() As String
            Get
                Return fState
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("State", fState, value)
            End Set
        End Property
        Dim fZip As String
        Public Property Zip() As String
            Get
                Return fZip
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Zip", fZip, value)
            End Set
        End Property
        Dim fCountry As Countries
        Public Property Country() As Countries
            Get
                Return fCountry
            End Get
            Set(ByVal value As Countries)
                SetPropertyValue(Of Countries)("Country", fCountry, value)
            End Set
        End Property
        Dim fPhone As String
        Public Property Phone() As String
            Get
                Return fPhone
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Phone", fPhone, value)
            End Set
        End Property
        Dim fFax As String
        Public Property Fax() As String
            Get
                Return fFax
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Fax", fFax, value)
            End Set
        End Property
        Dim fEmail As String
        Public Property Email() As String
            Get
                Return fEmail
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Email", fEmail, value)
            End Set
        End Property
        Dim fCreditLimit As Double
        Public Property CreditLimit() As Double
            Get
                Return fCreditLimit
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("CreditLimit", fCreditLimit, value)
            End Set
        End Property
        Dim fOpeningBalance As Double
        Public Property OpeningBalance() As Double
            Get
                Return fOpeningBalance
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("OpeningBalance", fOpeningBalance, value)
            End Set
        End Property
        Dim fCreateBusinesSource As Boolean
        Public Property CreateBusinesSource() As Boolean
            Get
                Return fCreateBusinesSource
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("CreateBusinesSource", fCreateBusinesSource, value)
            End Set
        End Property
        Dim fRegNo As String
        Public Property RegNo() As String
            Get
                Return fRegNo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RegNo", fRegNo, value)
            End Set
        End Property
        Dim fRegNo1 As String
        Public Property RegNo1() As String
            Get
                Return fRegNo1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RegNo1", fRegNo1, value)
            End Set
        End Property
        Dim fRegNo2 As String
        Public Property RegNo2() As String
            Get
                Return fRegNo2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RegNo2", fRegNo2, value)
            End Set
        End Property
        Dim fAccountType As CityLedgerTypes
        Public Property AccountType() As CityLedgerTypes
            Get
                Return fAccountType
            End Get
            Set(ByVal value As CityLedgerTypes)
                SetPropertyValue(Of CityLedgerTypes)("AccountType", fAccountType, value)
            End Set
        End Property
        Dim fCreatedOn As String
        Public Property CreatedOn() As String
            Get
                Return fCreatedOn
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CreatedOn", fCreatedOn, value)
            End Set
        End Property
        Dim fCreatedBy As String
        Public Property CreatedBy() As String
            Get
                Return fCreatedBy
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CreatedBy", fCreatedBy, value)
            End Set
        End Property
        Dim fCardNo As String
        Public Property CardNo() As String
            Get
                Return fCardNo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CardNo", fCardNo, value)
            End Set
        End Property
        Dim fAcNo As String
        Public Property AcNo() As String
            Get
                Return fAcNo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AcNo", fAcNo, value)
            End Set
        End Property
        Dim fHotelRepresentative As String
        Public Property HotelRepresentative() As String
            Get
                Return fHotelRepresentative
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("HotelRepresentative", fHotelRepresentative, value)
            End Set
        End Property
    End Class

End Namespace
