'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    <DeferredDeletion(True)> _
    Partial Public Class BusinessSources
        Inherits XPObject
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fCompanyName As String
        Public Property CompanyName() As String
            Get
                Return fCompanyName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CompanyName", fCompanyName, value)
            End Set
        End Property
        Dim fAddress As String
        Public Property Address() As String
            Get
                Return fAddress
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Address", fAddress, value)
            End Set
        End Property
        Dim fCity As String
        Public Property City() As String
            Get
                Return fCity
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("City", fCity, value)
            End Set
        End Property
        Dim fZip As String
        Public Property Zip() As String
            Get
                Return fZip
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Zip", fZip, value)
            End Set
        End Property
        Dim fState As String
        Public Property State() As String
            Get
                Return fState
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("State", fState, value)
            End Set
        End Property
        Dim fCountry As Countries
        Public Property Country() As Countries
            Get
                Return fCountry
            End Get
            Set(ByVal value As Countries)
                SetPropertyValue(Of Countries)("Country", fCountry, value)
            End Set
        End Property
        Dim fPhone As String
        Public Property Phone() As String
            Get
                Return fPhone
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Phone", fPhone, value)
            End Set
        End Property
        Dim fFax As String
        Public Property Fax() As String
            Get
                Return fFax
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Fax", fFax, value)
            End Set
        End Property
        Dim fWebsite As String
        Public Property Website() As String
            Get
                Return fWebsite
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Website", fWebsite, value)
            End Set
        End Property
        Dim fEmail As String
        Public Property Email() As String
            Get
                Return fEmail
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Email", fEmail, value)
            End Set
        End Property
        Dim fDescription As String
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        Dim fIATANo As String
        Public Property IATANo() As String
            Get
                Return fIATANo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("IATANo", fIATANo, value)
            End Set
        End Property
        Dim fRegNo As String
        Public Property RegNo() As String
            Get
                Return fRegNo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RegNo", fRegNo, value)
            End Set
        End Property
        Dim fRegNo1 As String
        Public Property RegNo1() As String
            Get
                Return fRegNo1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RegNo1", fRegNo1, value)
            End Set
        End Property
        Dim fRegNo2 As String
        Public Property RegNo2() As String
            Get
                Return fRegNo2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RegNo2", fRegNo2, value)
            End Set
        End Property
        Dim fMarketPlace As String
        Public Property MarketPlace() As String
            Get
                Return fMarketPlace
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MarketPlace", fMarketPlace, value)
            End Set
        End Property
        Dim fCharter As Boolean
        Public Property Charter() As Boolean
            Get
                Return fCharter
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("Charter", fCharter, value)
            End Set
        End Property
        Dim fCharterColor As String
        Public Property CharterColor() As String
            Get
                Return fCharterColor
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CharterColor", fCharterColor, value)
            End Set
        End Property
        Dim fHotelRepresentative As String
        Public Property HotelRepresentative() As String
            Get
                Return fHotelRepresentative
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("HotelRepresentative", fHotelRepresentative, value)
            End Set
        End Property
        Dim fAcNo As Integer
        Public Property AcNo() As Integer
            Get
                Return fAcNo
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("AcNo", fAcNo, value)
            End Set
        End Property
        Dim fPlan As String
        Public Property Plan() As String
            Get
                Return fPlan
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Plan", fPlan, value)
            End Set
        End Property
        Dim fValue As Integer
        Public Property Value() As Integer
            Get
                Return fValue
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Value", fValue, value)
            End Set
        End Property
        Dim fTerms As Integer
        Public Property Terms() As Integer
            Get
                Return fTerms
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Terms", fTerms, value)
            End Set
        End Property
        Dim fDefineSepcialRoomRates As Boolean
        Public Property DefineSepcialRoomRates() As Boolean
            Get
                Return fDefineSepcialRoomRates
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("DefineSepcialRoomRates", fDefineSepcialRoomRates, value)
            End Set
        End Property
        Dim fDefineSpecialSeason As Boolean
        Public Property DefineSpecialSeason() As Boolean
            Get
                Return fDefineSpecialSeason
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("DefineSpecialSeason", fDefineSpecialSeason, value)
            End Set
        End Property
        Dim fCreateAccount As Boolean
        Public Property CreateAccount() As Boolean
            Get
                Return fCreateAccount
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("CreateAccount", fCreateAccount, value)
            End Set
        End Property
        Dim fActive As Boolean
        Public Property Active() As Boolean
            Get
                Return fActive
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("Active", fActive, value)
            End Set
        End Property
    End Class

End Namespace
