'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class CashDrawer
        Inherits XPObject
        Dim fCurrency As Double
        Public Property Currency() As Double
            Get
                Return fCurrency
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("Currency", fCurrency, value)
            End Set
        End Property
        Dim fCurrencySign As String
        Public Property CurrencySign() As String
            Get
                Return fCurrencySign
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CurrencySign", fCurrencySign, value)
            End Set
        End Property
    End Class

End Namespace
