'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class Charter
        Inherits XPObject
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fSourceType As String
        Public Property SourceType() As String
            Get
                Return fSourceType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SourceType", fSourceType, value)
            End Set
        End Property
        Dim fSource As String
        Public Property Source() As String
            Get
                Return fSource
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Source", fSource, value)
            End Set
        End Property
        Dim fFromDate As String
        Public Property FromDate() As String
            Get
                Return fFromDate
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("FromDate", fFromDate, value)
            End Set
        End Property
        Dim fToDate As String
        Public Property ToDate() As String
            Get
                Return fToDate
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ToDate", fToDate, value)
            End Set
        End Property
        Dim fRemark As String
        Public Property Remark() As String
            Get
                Return fRemark
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Remark", fRemark, value)
            End Set
        End Property
        Dim fRelaseDays As Integer
        Public Property RelaseDays() As Integer
            Get
                Return fRelaseDays
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("RelaseDays", fRelaseDays, value)
            End Set
        End Property
    End Class

End Namespace
