'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    <DeferredDeletion(True)> _
    Partial Public Class ExchangeRates
        Inherits XPObject
        Dim fCountry As Countries
        Public Property Country() As Countries
            Get
                Return fCountry
            End Get
            Set(ByVal value As Countries)
                SetPropertyValue(Of Countries)("Country", fCountry, value)
            End Set
        End Property
        Dim fCurrency As String
        Public Property Currency() As String
            Get
                Return fCurrency
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Currency", fCurrency, value)
            End Set
        End Property
        Dim fSign As String
        Public Property Sign() As String
            Get
                Return fSign
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Sign", fSign, value)
            End Set
        End Property
        Dim fSignAs As String
        Public Property SignAs() As String
            Get
                Return fSignAs
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SignAs", fSignAs, value)
            End Set
        End Property
        Dim fDecimalPlaces As Double
        Public Property DecimalPlaces() As Double
            Get
                Return fDecimalPlaces
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("DecimalPlaces", fDecimalPlaces, value)
            End Set
        End Property
        Dim fDolarNo As Double
        Public Property DolarNo() As Double
            Get
                Return fDolarNo
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("DolarNo", fDolarNo, value)
            End Set
        End Property
        Dim fCurrencyNo As Double
        Public Property CurrencyNo() As Double
            Get
                Return fCurrencyNo
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("CurrencyNo", fCurrencyNo, value)
            End Set
        End Property
        Dim fActive As String
        Public Property Active() As String
            Get
                Return fActive
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Active", fActive, value)
            End Set
        End Property
    End Class

End Namespace
