'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    <DeferredDeletion(True)> _
    Partial Public Class DefineTariff
        Inherits XPObject
        Dim fRoomType As RoomTypes
        Public Property RoomType() As RoomTypes
            Get
                Return fRoomType
            End Get
            Set(ByVal value As RoomTypes)
                SetPropertyValue(Of RoomTypes)("RoomType", fRoomType, value)
            End Set
        End Property
        Dim fRateType As RateTypes
        Public Property RateType() As RateTypes
            Get
                Return fRateType
            End Get
            Set(ByVal value As RateTypes)
                SetPropertyValue(Of RateTypes)("RateType", fRateType, value)
            End Set
        End Property
        Dim fSeasonType As String
        Public Property SeasonType() As String
            Get
                Return fSeasonType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SeasonType", fSeasonType, value)
            End Set
        End Property
        Dim fSeason As Seasons
        Public Property Season() As Seasons
            Get
                Return fSeason
            End Get
            Set(ByVal value As Seasons)
                SetPropertyValue(Of Seasons)("Season", fSeason, value)
            End Set
        End Property
        Dim fTariff As Double
        Public Property Tariff() As Double
            Get
                Return fTariff
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("Tariff", fTariff, value)
            End Set
        End Property
        Dim fExtraAdult As Double
        Public Property ExtraAdult() As Double
            Get
                Return fExtraAdult
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("ExtraAdult", fExtraAdult, value)
            End Set
        End Property
        Dim fExtraChild As Double
        Public Property ExtraChild() As Double
            Get
                Return fExtraChild
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("ExtraChild", fExtraChild, value)
            End Set
        End Property
    End Class

End Namespace
