'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    <DeferredDeletion(True)> _
    Partial Public Class GRMMasters
        Inherits XPObject
        Dim fMaster As Masters
        Public Property Master() As Masters
            Get
                Return fMaster
            End Get
            Set(ByVal value As Masters)
                SetPropertyValue(Of Masters)("Master", fMaster, value)
            End Set
        End Property
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
    End Class

End Namespace
