'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class MealPlan
        Inherits XPObject
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fDescription As String
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        Dim fSortKey As String
        Public Property SortKey() As String
            Get
                Return fSortKey
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SortKey", fSortKey, value)
            End Set
        End Property
        Dim fPrefix As String
        Public Property Prefix() As String
            Get
                Return fPrefix
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Prefix", fPrefix, value)
            End Set
        End Property
        Dim fStartFrom As String
        Public Property StartFrom() As String
            Get
                Return fStartFrom
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("StartFrom", fStartFrom, value)
            End Set
        End Property
        Dim fAdvancedSetting As String
        Public Property AdvancedSetting() As String
            Get
                Return fAdvancedSetting
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AdvancedSetting", fAdvancedSetting, value)
            End Set
        End Property
    End Class

End Namespace
