'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class NonRentalObjects
        Inherits XPObject
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fDescription As String
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        Dim fType As String
        Public Property Type() As String
            Get
                Return fType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Type", fType, value)
            End Set
        End Property
        Dim fFloor As Floors
        Public Property Floor() As Floors
            Get
                Return fFloor
            End Get
            Set(ByVal value As Floors)
                SetPropertyValue(Of Floors)("Floor", fFloor, value)
            End Set
        End Property
        Dim fHPosition As Integer
        Public Property HPosition() As Integer
            Get
                Return fHPosition
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("HPosition", fHPosition, value)
            End Set
        End Property
        Dim fHeight As Integer
        Public Property Height() As Integer
            Get
                Return fHeight
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Height", fHeight, value)
            End Set
        End Property
        Dim fVPosition As Integer
        Public Property VPosition() As Integer
            Get
                Return fVPosition
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("VPosition", fVPosition, value)
            End Set
        End Property
        Dim fWidth As Integer
        Public Property Width() As Integer
            Get
                Return fWidth
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Width", fWidth, value)
            End Set
        End Property
        Dim fTextAlign As String
        Public Property TextAlign() As String
            Get
                Return fTextAlign
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("TextAlign", fTextAlign, value)
            End Set
        End Property
        Dim fBackColor As String
        Public Property BackColor() As String
            Get
                Return fBackColor
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BackColor", fBackColor, value)
            End Set
        End Property
        Dim fForColor As String
        Public Property ForColor() As String
            Get
                Return fForColor
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ForColor", fForColor, value)
            End Set
        End Property
        Dim fShowFont As Boolean
        Public Property ShowFont() As Boolean
            Get
                Return fShowFont
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("ShowFont", fShowFont, value)
            End Set
        End Property
        Dim fOutlet As String
        Public Property Outlet() As String
            Get
                Return fOutlet
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Outlet", fOutlet, value)
            End Set
        End Property
        Dim fRentItem As String
        Public Property RentItem() As String
            Get
                Return fRentItem
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RentItem", fRentItem, value)
            End Set
        End Property
        Dim fMinDeposit As Double
        Public Property MinDeposit() As Double
            Get
                Return fMinDeposit
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("MinDeposit", fMinDeposit, value)
            End Set
        End Property
        Dim fOwner As RoomOwner
        Public Property Owner() As RoomOwner
            Get
                Return fOwner
            End Get
            Set(ByVal value As RoomOwner)
                SetPropertyValue(Of RoomOwner)("Owner", fOwner, value)
            End Set
        End Property
    End Class

End Namespace
