'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    <DeferredDeletion(True)> _
    Partial Public Class RateTypes
        Inherits XPObject
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fDescription As String
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        Dim fSortKey As UInteger
        Public Property SortKey() As UInteger
            Get
                Return fSortKey
            End Get
            Set(ByVal value As UInteger)
                SetPropertyValue(Of UInteger)("SortKey", fSortKey, value)
            End Set
        End Property
        Dim fWebRateType As Boolean
        Public Property WebRateType() As Boolean
            Get
                Return fWebRateType
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("WebRateType", fWebRateType, value)
            End Set
        End Property
        Dim fHours As Integer
        Public Property Hours() As Integer
            Get
                Return fHours
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Hours", fHours, value)
            End Set
        End Property
        Dim fDays As Integer
        Public Property Days() As Integer
            Get
                Return fDays
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Days", fDays, value)
            End Set
        End Property
        Dim fActive As Boolean
        Public Property Active() As Boolean
            Get
                Return fActive
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("Active", fActive, value)
            End Set
        End Property
    End Class

End Namespace
