'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class Resons
        Inherits XPObject
        Dim fCategory As String
        Public Property Category() As String
            Get
                Return fCategory
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Category", fCategory, value)
            End Set
        End Property
        Dim fReason As String
        Public Property Reason() As String
            Get
                Return fReason
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Reason", fReason, value)
            End Set
        End Property
    End Class

End Namespace
