'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class RoomSize
        Inherits XPObject
        Dim fRoom As String
        Public Property Room() As String
            Get
                Return fRoom
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Room", fRoom, value)
            End Set
        End Property
        Dim fRoomType As String
        Public Property RoomType() As String
            Get
                Return fRoomType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RoomType", fRoomType, value)
            End Set
        End Property
        Dim fFloor As String
        Public Property Floor() As String
            Get
                Return fFloor
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Floor", fFloor, value)
            End Set
        End Property
        Dim fHeight As Integer
        Public Property Height() As Integer
            Get
                Return fHeight
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Height", fHeight, value)
            End Set
        End Property
        Dim fWidth As Integer
        Public Property Width() As Integer
            Get
                Return fWidth
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Width", fWidth, value)
            End Set
        End Property
    End Class

End Namespace
