'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    <DeferredDeletion(True)> _
    Partial Public Class RoomTypes
        Inherits XPObject
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fDescription As String
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        Dim fSortKey As Integer
        Public Property SortKey() As Integer
            Get
                Return fSortKey
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("SortKey", fSortKey, value)
            End Set
        End Property
        Dim fRate As Double
        Public Property Rate() As Double
            Get
                Return fRate
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("Rate", fRate, value)
            End Set
        End Property
        Dim fAdultRate As Double
        Public Property AdultRate() As Double
            Get
                Return fAdultRate
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("AdultRate", fAdultRate, value)
            End Set
        End Property
        Dim fChildRate As Double
        Public Property ChildRate() As Double
            Get
                Return fChildRate
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("ChildRate", fChildRate, value)
            End Set
        End Property
        Dim fOverBookingPercent As Double
        Public Property OverBookingPercent() As Double
            Get
                Return fOverBookingPercent
            End Get
            Set(ByVal value As Double)
                SetPropertyValue(Of Double)("OverBookingPercent", fOverBookingPercent, value)
            End Set
        End Property
        Dim fBaseAdult As Integer
        Public Property BaseAdult() As Integer
            Get
                Return fBaseAdult
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("BaseAdult", fBaseAdult, value)
            End Set
        End Property
        Dim fBaseChild As Integer
        Public Property BaseChild() As Integer
            Get
                Return fBaseChild
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("BaseChild", fBaseChild, value)
            End Set
        End Property
        Dim fMaxAdult As Integer
        Public Property MaxAdult() As Integer
            Get
                Return fMaxAdult
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("MaxAdult", fMaxAdult, value)
            End Set
        End Property
        Dim fMaxChild As Integer
        Public Property MaxChild() As Integer
            Get
                Return fMaxChild
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("MaxChild", fMaxChild, value)
            End Set
        End Property
        Dim fBackhColor As String
        Public Property BackhColor() As String
            Get
                Return fBackhColor
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BackhColor", fBackhColor, value)
            End Set
        End Property
        Dim fForColor As String
        Public Property ForColor() As String
            Get
                Return fForColor
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ForColor", fForColor, value)
            End Set
        End Property
        Dim fLowInventory As Integer
        Public Property LowInventory() As Integer
            Get
                Return fLowInventory
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("LowInventory", fLowInventory, value)
            End Set
        End Property
        Dim fHighInvEntory As String
        Public Property HighInvEntory() As String
            Get
                Return fHighInvEntory
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("HighInvEntory", fHighInvEntory, value)
            End Set
        End Property
        Dim fUploadInventoryDeductBy As Integer
        Public Property UploadInventoryDeductBy() As Integer
            Get
                Return fUploadInventoryDeductBy
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("UploadInventoryDeductBy", fUploadInventoryDeductBy, value)
            End Set
        End Property
        Dim fPercent As Boolean
        Public Property Percent() As Boolean
            Get
                Return fPercent
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("Percent", fPercent, value)
            End Set
        End Property
    End Class

End Namespace
