'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class Seasons
        Inherits XPObject
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fSeasonType As SeasonTypes
        Public Property SeasonType() As SeasonTypes
            Get
                Return fSeasonType
            End Get
            Set(ByVal value As SeasonTypes)
                SetPropertyValue(Of SeasonTypes)("SeasonType", fSeasonType, value)
            End Set
        End Property
        Dim fDescription As String
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        Dim fSource As String
        Public Property Source() As String
            Get
                Return fSource
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Source", fSource, value)
            End Set
        End Property
        Dim fFromDate As DateTime
        Public Property FromDate() As DateTime
            Get
                Return fFromDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FromDate", fFromDate, value)
            End Set
        End Property
        Dim fToDate As DateTime
        Public Property ToDate() As DateTime
            Get
                Return fToDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("ToDate", fToDate, value)
            End Set
        End Property
    End Class

End Namespace
