'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class StatementType
        Inherits XPObject
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fField1 As String
        Public Property Field1() As String
            Get
                Return fField1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Field1", fField1, value)
            End Set
        End Property
        Dim fPaymentOptions As String
        Public Property PaymentOptions() As String
            Get
                Return fPaymentOptions
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PaymentOptions", fPaymentOptions, value)
            End Set
        End Property
    End Class

End Namespace
