'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class SubBusinessSource
        Inherits XPObject
        Dim fSource As String
        Public Property Source() As String
            Get
                Return fSource
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Source", fSource, value)
            End Set
        End Property
        Dim fSourceType As String
        Public Property SourceType() As String
            Get
                Return fSourceType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SourceType", fSourceType, value)
            End Set
        End Property
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
    End Class

End Namespace
