'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Salling.HOTELS.ORM

    Partial Public Class TransportationSchedual
        Inherits XPObject
        Dim fModel As String
        Public Property Model() As String
            Get
                Return fModel
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Model", fModel, value)
            End Set
        End Property
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fDescription As String
        Public Property Description() As String
            Get
                Return fDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Description", fDescription, value)
            End Set
        End Property
        Dim fStation As Stations
        Public Property Station() As Stations
            Get
                Return fStation
            End Get
            Set(ByVal value As Stations)
                SetPropertyValue(Of Stations)("Station", fStation, value)
            End Set
        End Property
        Dim fArrivalTime As String
        Public Property ArrivalTime() As String
            Get
                Return fArrivalTime
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArrivalTime", fArrivalTime, value)
            End Set
        End Property
        Dim fDepatureTime As String
        Public Property DepatureTime() As String
            Get
                Return fDepatureTime
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DepatureTime", fDepatureTime, value)
            End Set
        End Property
        Dim fArrivalDay As String
        Public Property ArrivalDay() As String
            Get
                Return fArrivalDay
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ArrivalDay", fArrivalDay, value)
            End Set
        End Property
        Dim fDepatureDay As String
        Public Property DepatureDay() As String
            Get
                Return fDepatureDay
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DepatureDay", fDepatureDay, value)
            End Set
        End Property
    End Class

End Namespace
