Imports System.Data

Namespace Salling.Report.Scripting
    Public Class SupportedScript
        Private Shared mySupportedScriptTable As New DataTable()

        Public Shared ReadOnly Property SupportedScriptNameCount() As Integer
            Get
                Return SupportedScript.mySupportedScriptTable.Rows.Count
            End Get
        End Property

        Shared Sub New()
            SupportedScript.mySupportedScriptTable.Columns.Add("Category")
            SupportedScript.mySupportedScriptTable.Columns.Add("ScriptName")
            SupportedScript.mySupportedScriptTable.Columns.Add("Description")
            SupportedScript.mySupportedScriptTable.PrimaryKey = New DataColumn(0) {SupportedScript.mySupportedScriptTable.Columns("ScriptName")}
            SupportedScript.AddDefaultScriptNames()
        End Sub

        Private Shared Sub AddDefaultScriptNames()
            Dim dataTable As DataTable = SupportedScript.mySupportedScriptTable
            dataTable.Rows.Add(DirectCast("Others", Object), DirectCast("Application", Object), DirectCast("Application", Object))
            dataTable.Rows.Add(DirectCast("SerialNumber", Object), DirectCast("SerialNoEntryForm", Object), DirectCast("Serial Number Entry Form", Object))
            dataTable.Rows.Add(DirectCast("SerialNumber", Object), DirectCast("SerialNoEntrySAForm", Object), DirectCast("Serial Number Entry Form For Item Opening", Object))
            dataTable.Rows.Add(DirectCast("SerialNumber", Object), DirectCast("SerialNoEntryTransferForm", Object), DirectCast("Serial Number Entry Form For Document Transfer", Object))
            dataTable.Rows.Add(DirectCast("Inquiry", Object), DirectCast("ItemInquiry", Object), DirectCast("Stock Item Inquiry", Object))
            dataTable.Rows.Add(DirectCast("Inquiry", Object), DirectCast("AccountInquiry", Object), DirectCast("Account Inquiry", Object))
            dataTable.Rows.Add(DirectCast("InstantInfo", Object), DirectCast("UCInquiry", Object), DirectCast("Invoicing Instant Info", Object))
            dataTable.Rows.Add(DirectCast("InstantInfo", Object), DirectCast("UCInquiryCSGN", Object), DirectCast("Instant Info with Consignment Info", Object))
            dataTable.Rows.Add(DirectCast("InstantInfo", Object), DirectCast("UCInquiryStock", Object), DirectCast("Stock Instant Info", Object))
            dataTable.Rows.Add(DirectCast("Report", Object), DirectCast("ReorderAdvice", Object), DirectCast("Reorder Advice", Object))
            dataTable.Rows.Add(DirectCast("Report", Object), DirectCast("PrintBarCode", Object), DirectCast("Print Bar Code", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("Debtor", Object), DirectCast("Debtor", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("Creditor", Object), DirectCast("Creditor", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("DebtorType", Object), DirectCast("Debtor Type", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("CreditorType", Object), DirectCast("Creditor Type", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("Item", Object), DirectCast("Stock Item", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemCommand", Object), DirectCast("Stock Item Command Form", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemListing", Object), DirectCast("Print Stock Item Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemEditForm", Object), DirectCast("Stock Item Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemSearch", Object), DirectCast("Stock Item Search Form", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemGroup", Object), DirectCast("Stock Group", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemType", Object), DirectCast("Stock Item Type", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemPackage", Object), DirectCast("Item Package", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemPackageCommandForm", Object), DirectCast("Item Package Command Form", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemPackageEntry", Object), DirectCast("Item Package Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemPackagePrintListing", Object), DirectCast("Print Item Package Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemBOM", Object), DirectCast("Item BOM", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemBOMCommandForm", Object), DirectCast("Item BOM Command Form", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("ItemBOMEditForm", Object), DirectCast("Item BOM Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("Project", Object), DirectCast("Project", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("Department", Object), DirectCast("Department", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("PriceCategory", Object), DirectCast("Price Category", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("TaxType", Object), DirectCast("Tax Type", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("DNType", Object), DirectCast("D/N Type", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("CNType", Object), DirectCast("C/N Type", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("Currency", Object), DirectCast("Currency", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("CurrRate", Object), DirectCast("Currency Rate", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("Journal", Object), DirectCast("Journal Type", Object))
            dataTable.Rows.Add(DirectCast("Maintenance", Object), DirectCast("PaymentMethod", Object), DirectCast("Payment Method", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("ADJ", Object), DirectCast("Stock Adjustment", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockAdjustmentCommandForm", Object), DirectCast("Stock Adjustment Command Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockAdjustmentEditForm", Object), DirectCast("Stock Adjustment Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockAdjustmentListing", Object), DirectCast("Print Stock Adjustment Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockAdjustmentDetailListing", Object), DirectCast("Print Stock Adjustment Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("ISS", Object), DirectCast("Stock Issue", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockIssueCommandForm", Object), DirectCast("Stock Issue Command Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockIssueEditForm", Object), DirectCast("Stock Issue Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockIssueListing", Object), DirectCast("Print Stock Issue Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockIssueDetailListing", Object), DirectCast("Print Stock Issue Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("RCV", Object), DirectCast("Stock Receive", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockReceiveCommandForm", Object), DirectCast("Stock Receive Command Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockReceiveEditForm", Object), DirectCast("Stock Receive Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockReceiveListing", Object), DirectCast("Print Stock Receive Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockReceiveDetailListing", Object), DirectCast("Print Stock Receive Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("WOFF", Object), DirectCast("Stock Write-Off", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockWriteOffCommandForm", Object), DirectCast("Stock Write Off Command Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockWriteOffEditForm", Object), DirectCast("Stock Write Off Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockWriteOffListing", Object), DirectCast("Print Stock Write Off Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockWriteOffDetailListing", Object), DirectCast("Print Stock Write Off Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("UOMCONV", Object), DirectCast("Stock UOM Conversion", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockUOMConversionCommandForm", Object), DirectCast("Stock UOM Conversion Command Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockUOMConversionEditForm", Object), DirectCast("Stock UOM Conversion Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockUOMConversionListing", Object), DirectCast("Print Stock UOM Conversion Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockUOMConversionDetailListing", Object), DirectCast("Print Stock UOM Conversion Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("UPDATECOST", Object), DirectCast("Stock Update Cost", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockUpdateCostCommandForm", Object), DirectCast("Stock Update Cost Command Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockUpdateCostEditForm", Object), DirectCast("Stock Update Cost Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockUpdateCostListing", Object), DirectCast("Print Stock Update Cost Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockUpdateCostDetailListing", Object), DirectCast("Print Stock Update Cost Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("XFER", Object), DirectCast("Stock Transfer", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockTransferCommandForm", Object), DirectCast("Stock Transfer Command Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockTransferEditForm", Object), DirectCast("Stock Transfer Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockTransferListing", Object), DirectCast("Print Stock Transfer Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Stock", Object), DirectCast("StockTransferDetailListing", Object), DirectCast("Print Stock Transfer Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Manufacturing", Object), DirectCast("ASM", Object), DirectCast("Stock Assembly", Object))
            dataTable.Rows.Add(DirectCast("Manufacturing", Object), DirectCast("StockAssemblyCommandForm", Object), DirectCast("Stock Assembly Command Form", Object))
            dataTable.Rows.Add(DirectCast("Manufacturing", Object), DirectCast("StockAssemblyEditForm", Object), DirectCast("Stock Assembly Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Manufacturing", Object), DirectCast("StockAssemblyListing", Object), DirectCast("Print Stock Assembly Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Manufacturing", Object), DirectCast("StockAssemblyDetailListing", Object), DirectCast("Print Stock Assembly Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Manufacturing", Object), DirectCast("ASMORDER", Object), DirectCast("Stock Assembly Order", Object))
            dataTable.Rows.Add(DirectCast("Manufacturing", Object), DirectCast("StockAssemblyOrderCommandForm", Object), DirectCast("Stock Assembly Order Command Form", Object))
            dataTable.Rows.Add(DirectCast("Manufacturing", Object), DirectCast("StockAssemblyOrderEditForm", Object), DirectCast("Stock Assembly Order Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Manufacturing", Object), DirectCast("StockAssemblyOrderListing", Object), DirectCast("Print Stock Assembly Order Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Manufacturing", Object), DirectCast("StockAssemblyOrderDetailListing", Object), DirectCast("Print Stock Assembly Order Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("CB", Object), DirectCast("Cash Book Entry", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("CashBookCommandForm", Object), DirectCast("Cash Book Command Form", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("CashBookListing", Object), DirectCast("Print Cash Book Listing Form", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("CashBookEditForm", Object), DirectCast("Cash Book Edit Form", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("JE", Object), DirectCast("Journal Entry", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("JournalEntryCommandForm", Object), DirectCast("Journal Entry Command Form", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("JournalEntryListing", Object), DirectCast("Print Journal Entry Listing Form", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("JournalEntryEditForm", Object), DirectCast("Journal Entry Edit Form", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("BankRecon", Object), DirectCast("Bank Reconciliation", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("BankReconCommandForm", Object), DirectCast("Bank Reconciliation Command Form", Object))
            dataTable.Rows.Add(DirectCast("G/L", Object), DirectCast("BankReconEditForm", Object), DirectCast("Bank Reconciliation Edit Form", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARInvoice", Object), DirectCast("A/R Invoice", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARInvoiceCommandForm", Object), DirectCast("A/R Invoice Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARDN", Object), DirectCast("A/R Debit Note", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARDNCommandForm", Object), DirectCast("A/R Debit Note Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARCN", Object), DirectCast("A/R Credit Note", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARCNCommandForm", Object), DirectCast("A/R Credit Note Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARPayment", Object), DirectCast("A/R Payment", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARPaymentCommandForm", Object), DirectCast("A/R Payment Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARRefund", Object), DirectCast("A/R Refund", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARRefundCommandForm", Object), DirectCast("A/R Refund Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARAPContra", Object), DirectCast("A/R and A/P Contra", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARAPContraCommandForm", Object), DirectCast("A/R and A/P Contra Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARDeposit", Object), DirectCast("A/R Deposit", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARDepositCommandForm", Object), DirectCast("A/R Deposit Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/R", Object), DirectCast("ARAnalysisByDocument", Object), DirectCast("A/R Analysis By Document", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APInvoice", Object), DirectCast("A/P Invoice", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APInvoiceCommandForm", Object), DirectCast("A/P Invoice Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APDN", Object), DirectCast("A/P Debit Note", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APDNCommandForm", Object), DirectCast("A/P Debit Note Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APCN", Object), DirectCast("A/P Credit Note", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APCNCommandForm", Object), DirectCast("A/P Credit Note Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APPayment", Object), DirectCast("A/P Payment", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APPaymentCommandForm", Object), DirectCast("A/P Payment Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APRefund", Object), DirectCast("A/P Refund", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APRefundCommandForm", Object), DirectCast("A/P Refund Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APDeposit", Object), DirectCast("A/P Deposit", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APDepositCommandForm", Object), DirectCast("A/P Deposit Command Form", Object))
            dataTable.Rows.Add(DirectCast("A/P", Object), DirectCast("APAnalysisByDocument", Object), DirectCast("A/P Analysis By Document", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("QT", Object), DirectCast("Quotation", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("QuotationCommandForm", Object), DirectCast("Quotation Command Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("QuotationEditForm", Object), DirectCast("Quotation Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("QuotationListing", Object), DirectCast("Print Quotation Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("QuotationDetailListing", Object), DirectCast("Print Quotation Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("SO", Object), DirectCast("Sales Order", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("SalesOrderCommandForm", Object), DirectCast("Sales Order Command Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("SalesOrderEditForm", Object), DirectCast("Sales Order Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("SalesOrderListing", Object), DirectCast("Print Sales Order Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("SalesOrderDetailListing", Object), DirectCast("Print Sales Order Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DO", Object), DirectCast("Delivery Order", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DeliveryOrderCommandForm", Object), DirectCast("Delivery Order Command Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DeliveryOrderEditForm", Object), DirectCast("Delivery Order Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DeliveryOrderListing", Object), DirectCast("Print Delivery Order Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DeliveryOrderDetailListing", Object), DirectCast("Print Delivery Order Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("IV", Object), DirectCast("Invoice", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("InvoiceCommandForm", Object), DirectCast("Invoice Command Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("InvoiceEditForm", Object), DirectCast("Invoice Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("InvoiceListing", Object), DirectCast("Print Invoice Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("InvoiceDetailListing", Object), DirectCast("Print Invoice Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CS", Object), DirectCast("Cash Sale", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CashSaleCommandForm", Object), DirectCast("Cash Sale Command Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("POSCashSaleEditForm", Object), DirectCast("POS Cash Sale Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CashSaleEditForm", Object), DirectCast("Cash Sale Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CashSaleListing", Object), DirectCast("Print Cash Sale Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CashSaleDetailListing", Object), DirectCast("Print Cash Sale Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DN", Object), DirectCast("Debit Note", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DebitNoteCommandForm", Object), DirectCast("Debit Note Command Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DebitNoteEditForm", Object), DirectCast("Debit Note Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DebitNoteListing", Object), DirectCast("Print Debit Note Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DebitNoteDetailListing", Object), DirectCast("Print Debit Note Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CN", Object), DirectCast("Credit Note", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CreditNoteCommandForm", Object), DirectCast("Credit Note Command Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CreditNoteEditForm", Object), DirectCast("Credit Note Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CreditNoteListing", Object), DirectCast("Print Credit Note Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CreditNoteDetailListing", Object), DirectCast("Print Credit Note Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("XS", Object), DirectCast("Cancel S/O", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CancelSOCommandForm", Object), DirectCast("Cancel S/O Command Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CancelSOEditForm", Object), DirectCast("Cancel S/O Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CancelSOListing", Object), DirectCast("Print Cancel S/O Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CancelSODetailListing", Object), DirectCast("Print Cancel S/O Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DR", Object), DirectCast("Delivery Return", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DeliveryReturnCommandForm", Object), DirectCast("Delivery Return Command Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DeliveryReturnEditForm", Object), DirectCast("Delivery Return Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DeliveryReturnListing", Object), DirectCast("Print Delivery Return Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("DeliveryReturnDetailListing", Object), DirectCast("Print Delivery Return Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("CSGN", Object), DirectCast("Consignment", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("ConsignmentCommandForm", Object), DirectCast("Consignment Command Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("ConsignmentEditForm", Object), DirectCast("Consignment Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("ConsignmentListing", Object), DirectCast("Print Consignment Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Sales", Object), DirectCast("ConsignmentDetailListing", Object), DirectCast("Print Consignment Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("RQ", Object), DirectCast("Request for Quotation", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("RequestQuotationCommandForm", Object), DirectCast("Request Quotation Command Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("RequestQuotationEditForm", Object), DirectCast("Request Quotation Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("RequestQuotationListing", Object), DirectCast("Print Request Quotation Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("RequestQuotationDetailListing", Object), DirectCast("Print Request Quotation Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PO", Object), DirectCast("Purchase Order", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseOrderCommandForm", Object), DirectCast("Purchase Order Command Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseOrderEditForm", Object), DirectCast("Purchase Order Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseOrderListing", Object), DirectCast("Print Purchase Order Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseOrderDetailListing", Object), DirectCast("Print Purchase Order Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("GR", Object), DirectCast("Goods Received Note", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("GoodsReceivedNoteCommandForm", Object), DirectCast("Goods Received Note Command Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("GoodsReceivedNoteEditForm", Object), DirectCast("Goods Received Note Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("GoodsReceivedNoteListing", Object), DirectCast("Print Goods Received Note Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("GoodsReceivedNoteDetailListing", Object), DirectCast("Print Goods Received Note Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PI", Object), DirectCast("Purchase Invoice", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseInvoiceCommandForm", Object), DirectCast("Purchase Invoice Command Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseInvoiceEditForm", Object), DirectCast("Purchase Invoice Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseInvoiceListing", Object), DirectCast("Print Purchase Invoice Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseInvoiceDetailListing", Object), DirectCast("Print Purchase Invoice Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("CP", Object), DirectCast("Cash Purchase", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("CashPurchaseCommandForm", Object), DirectCast("Cash Purchase Command Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("CashPurchaseEditForm", Object), DirectCast("Cash Purchase Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("CashPurchaseListing", Object), DirectCast("Print Cash Purchase Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("CashPurchaseDetailListing", Object), DirectCast("Print Cash Purchase Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PR", Object), DirectCast("Purchase Return", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseReturnCommandForm", Object), DirectCast("Purchase Return Command Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseReturnEditForm", Object), DirectCast("Purchase Return Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseReturnListing", Object), DirectCast("Print Purchase Return Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("PurchaseReturnDetailListing", Object), DirectCast("Print Purchase Return Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("XP", Object), DirectCast("Cancel P/O", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("CancelPOCommandForm", Object), DirectCast("Cancel P/O Command Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("CancelPOEditForm", Object), DirectCast("Cancel P/O Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("CancelPOListing", Object), DirectCast("Print Cancel P/O Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("CancelPODetailListing", Object), DirectCast("Print Cancel P/O Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("GT", Object), DirectCast("Goods Return", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("GoodsReturnCommandForm", Object), DirectCast("Goods Return Command Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("GoodsReturnEditForm", Object), DirectCast("Goods Return Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("GoodsReturnListing", Object), DirectCast("Print Goods Return Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("GoodsReturnDetailListing", Object), DirectCast("Print Goods Return Detail Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("SupplierCSGN", Object), DirectCast("Supplier Consignment", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("SupplierConsignmentCommandForm", Object), DirectCast("Supplier Consignment Command Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("SupplierConsignmentEditForm", Object), DirectCast("Supplier Consignment Edit Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("SupplierConsignmentListing", Object), DirectCast("Print Supplier Consignment Listing Form", Object))
            dataTable.Rows.Add(DirectCast("Purchase", Object), DirectCast("SupplierConsignmentDetailListing", Object), DirectCast("Print Supplier Consignment Detail Listing Form", Object))
        End Sub

        Public Shared Sub AddSupportedScriptName(scriptName As String, category As String, description As String)
            If SupportedScript.mySupportedScriptTable.Rows.Find(DirectCast(scriptName, Object)) IsNot Nothing Then
                Return
            End If
            SupportedScript.mySupportedScriptTable.Rows.Add(DirectCast(category, Object), DirectCast(scriptName, Object), DirectCast(description, Object))
        End Sub

        Public Shared Function GetScriptDescription(scriptName As String) As String
            Dim dataRow As DataRow = SupportedScript.mySupportedScriptTable.Rows.Find(DirectCast(scriptName, Object))
            If dataRow IsNot Nothing Then
                Return dataRow("Description").ToString()
            End If
            Return ""
        End Function

        Public Shared Sub GetSupportedScriptNameInfo(index As Integer, ByRef scriptName As String, ByRef category As String, ByRef description As String)
            Dim dataRow As DataRow = SupportedScript.mySupportedScriptTable.Rows(index)
            scriptName = dataRow("ScriptName").ToString()
            category = dataRow("Category").ToString()
            description = dataRow("Description").ToString()
        End Sub
    End Class
End Namespace